### ISSUE TITLE
ETA for the source code release

### ISSUE THREAD

**Issue by piotr-jozwiak** [ruizhecao96/CMGAN#1]
Hey,

Do you have an ETA for the release of the CMGAN source code?

Thanks!

**Comment by ruizhecao96** [comment]
> Hey,
> 
> Do you have an ETA for the release of the CMGAN source code?
> 
> Thanks!

Hi!
We are planning to release the source code in the middle of June as now there are still some tests that should be done.
Best regards

**Comment by AlonKellner** [comment]
Hi! Is June still feasible for the source code release?
Really excited about it :)

**Comment by ruizhecao96** [comment]
I am sorry that there are some issues and we can't release it now, but we will release the code in two weeks!
