### ISSUE TITLE
When the GPU is occupied

### ISSUE THREAD

**Issue by MaNing1924382115** [ruizhecao96/CMGAN#10]
run  evaluation.py  
When the GPU is occupied, for example, how big the GPU needs to be in 20 seconds

**Comment by SherifAbdulatif** [comment]
You mean if you give a 20 seconds track what is the GPU utilization in inference?

**Comment by daniel-nocap** [comment]
I am experiencing CUDA out of memory errors on a GPU with 40gb of memory whenever I perform inference on an audio file longer than 10 seconds. There is a massive spike in GPU memory utilization at this line in evaluation.py:
`est_real, est_imag = model(noisy_spec)`

Any suggestions for how to reduce peak memory usage would be greatly appreciated. Thank you

**Comment by ruizhecao96** [comment]
> I am experiencing CUDA out of memory errors on a GPU with 40gb of memory whenever I perform inference on an audio file longer than 10 seconds. There is a massive spike in GPU memory utilization at this line in evaluation.py: `est_real, est_imag = model(noisy_spec)`
> 
> Any suggestions for how to reduce peak memory usage would be greatly appreciated. Thank you

Just reshape the input, for example you have 20 seconds track, then reshape it from (1, 16000*20) to (2, 16000*10) or (4, 16000*5), and reshape it back in the output. Since the computational complexity increase quadratically with the increase of the input length.
