### ISSUE TITLE
ComplexDecoder

### ISSUE THREAD

**Issue by lth456321** [ruizhecao96/CMGAN#13]
Hello, I found that compared with your paper, your code has a conv layer reduced in ComplexDecoder. Could you tell me the reason or if I misunderstand your paper/code? Thank you.

**Comment by SherifAbdulatif** [comment]
Thank you for your note. We originally planned it as the paper to have 2 layers at the end one with 64 channels and then we shrink it to 2 by last layer. According to the trials, the last convolution layer is enough, I don't think having this extra 64 layer will affect the scores that much though.
