### ISSUE TITLE
Extract estimated noise

### ISSUE THREAD

**Issue by Ludvig-Joborn** [ruizhecao96/CMGAN#14]
Hi!
First off, excellent paper and code! I learnt a lot about SE from the paper and find your code very well structured and clear. Thank you!

Now, what I'd like to be able to do is to extract the estimated noise (as opposed to the estimated speech). I have experimented a little with the code but not got been able to extract the noise. Is this supported by the model structure, and if so, how?

Kindest wishes.

**Comment by ruizhecao96** [comment]
Thanks for your interest! I think you can get the estimated noise by doing output minus input, since the noise is additive. Specifically, estimated noise = x - net(x), but make sure the input is normalized.

**Comment by Ludvig-Joborn** [comment]
Thanks Ruiz, turns out that the normalization was the missing ingredient. Just in case you're interested, the reason I seek the noise is to perhaps apply [RemixIT](https://arxiv.org/pdf/2202.08862.pdf) to the model such that I can try unsupervised domain adaptation.
Again, I learned a lot from the paper. So thanks for your work!
