### ISSUE TITLE
what python version this model work on ?

### ISSUE THREAD

**Issue by cyberfixer** [ruizhecao96/CMGAN#15]
it gives me this 

ERROR: Could not find a version that satisfies the requirement torch==1.10.0+cu113 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0)
ERROR: No matching distribution found for torch==1.10.0+cu113

I think I am using the wrong python version

**Comment by Ludvig-Joborn** [comment]
Try Python 3.9.13. That's at least what I'm using and everything seems to work just fine!

**Comment by ruizhecao96** [comment]
You can also try the new torch version, it should be compatible
