### ISSUE TITLE
Run-time Error

### ISSUE THREAD

**Issue by salmaShahid** [ruizhecao96/CMGAN#16]
Hey
can you please tell me how to resolve this error
It generates while running the python train.py file

Platform: Google Colaboratory

RuntimeError: CUDA out of memory. Tried to allocate 1.97 GiB (GPU 0; 14.76 GiB total capacity; 12.16 GiB already allocated; 1.04 GiB free; 12.32 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by ruizhecao96** [comment]
You can try reduce the batch size or reduce the cut length to 2 seconds or 1 second, but of course, the performance will decrease.
