### ISSUE TITLE
Does this program require a large amount of gpu memory？

### ISSUE THREAD

**Issue by DingChun-code** [ruizhecao96/CMGAN#19]
I tried to reproduce the code and found that although there are not many network parameters, it takes up 20g of GPU memory. Is the code I reproduced wrong?

**Comment by ruizhecao96** [comment]
Yes it requires large memories, the computational complexity of attention increase quadratically with the increase of the input length, you can reduce the length of track segmentation to reduce the memory cost.

**Comment by DingChun-code** [comment]
Thank you for your answer，I wonder if reducing the track length will affect the performance of the model？

**Comment by ruizhecao96** [comment]
Yes, of course, it has some impact because attention relies on long-distance dependency if you reduce the track length to 40ms or 80ms it will have an extensive drop.

**Comment by DingChun-code** [comment]
Sorry to bother you again, I try to use the code training model to use batch_ size=4，cut_ len=16000 * 2, and the model trained for 80 and 120 epochs was tested, but the two results were found to be lower than the result in the paper.

**Comment by ruizhecao96** [comment]
How much lower it is? If not much you can try to test with less epochs, as we train with only batch size of 3.

**Comment by DingChun-code** [comment]
the ssnr is only 10.4 in epoch=80, I want ask what method do you use to reduce the data to 16 khz.

**Comment by SherifAbdulatif** [comment]
You can use the librosa downsampling which is similar to torch:
audio_down, sr = librosa.load(audio_path, sr=16000)
