### ISSUE TITLE
Have you trained the model on the DNS Challenge dataset?

### ISSUE THREAD

**Issue by wangtiance** [ruizhecao96/CMGAN#2]
The samples you provided sound impressive! It would be nice to know how well the model works for the DNS challenge dataset.

**Comment by ruizhecao96** [comment]
I appreciate your interest in our work! Unfortunately, this model can not do the real-time job now, so we didn't train on the DNS challenge. But we will release some audio samples from the DNS test set for comparison later.

**Comment by wangtiance** [comment]
Thanks. I think you can still train on the DNS dataset for non real-time algorithms.
