### ISSUE TITLE
Real-time enhancement

### ISSUE THREAD

**Issue by zeynepgulhanuslu** [ruizhecao96/CMGAN#20]
Hi, 

Is this project working on real-time? If not, do you think I can adjust for real time.

Thank you

**Comment by ruizhecao96** [comment]
No, it's not real-time, you can try to change it to causal mode, but I am not sure how will the performance degrade

**Comment by zeynepgulhanuslu** [comment]
Thank you. Have a nice day

**Comment by KarmaYan** [comment]
> No, it's not real-time, you can try to change it to causal mode, but I am not sure how will the performance degrade

Hi, I would like to ask if you have finished the real time work and if the test result has a big regression compared to the original one?

**Comment by zeynepgulhanuslu** [comment]
Hi,

Sorry, I didn't have a time to do this. I couldn't try it yet. I hope you can do it, good luck.

**Comment by thinh93** [comment]
> > No, it's not real-time, you can try to change it to causal mode, but I am not sure how will the performance degrade
> 
> Hi, I would like to ask if you have finished the real time work and if the test result has a big regression compared to the original one?

Hi, Have you finished the real-time work yet? I am stuck on that.
