### ISSUE TITLE
RuntimeError: the derivative for 'angle' is not implemented

### ISSUE THREAD

**Issue by RenGuangyi** [ruizhecao96/CMGAN#24]
Hello! Thank you for your open source code！I changed the batch size to 3, but I encountered the following problems:
![image](https://user-images.githubusercontent.com/90442413/222886073-3c24d6c8-14ed-43c3-9995-d27a369dc638.png)

**Comment by DingChun-code** [comment]
"I think it may be related to the version of torch, and I have encountered this problem before. When I switched to a device with a higher version of torch, the problem disappeared."

**Comment by RenGuangyi** [comment]
Thank you for your reply！

**Comment by SherifAbdulatif** [comment]
I think you should keep the torch version as in requirements.
