### ISSUE TITLE
RuntimeError: NCCL error in: /……/.cpp:957, invalid usage, NCCL version 21.0.3

### ISSUE THREAD

**Issue by LiuBurger** [ruizhecao96/CMGAN#25]
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1634272204863/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:957, invalid usage, NCCL version 21.0.3

**Comment by utyanndesu** [comment]
I have also encountered this problem. Have you resolved it？

**Comment by LiuBurger** [comment]
Yes I have，but by an easy method：using DataParallel instead of DistributedDataParallel


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ruizhecao96/CMGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月18日(星期二) 晚上10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ruizhecao96/CMGAN] RuntimeError: NCCL error in: /……/.cpp:957, invalid usage, NCCL version 21.0.3 (Issue #25)





 
I have also encountered this problem. Have you resolved it？

**Comment by utyanndesu** [comment]
Thank you！But after this replacement, new errors appeared again

**Comment by LiuBurger** [comment]
You could use the code which is before the “Feature Multiple GPU Training” update，and try to modify it by using DataParallel




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ruizhecao96/CMGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月19日(星期三) 晚上6:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ruizhecao96/CMGAN] RuntimeError: NCCL error in: /……/.cpp:957, invalid usage, NCCL version 21.0.3 (Issue #25)





 
Thank you！But after this replacement, new errors appeared again

**Comment by utyanndesu** [comment]
Thank you very much for your suggestion, but as a beginner, I have encountered too many problems while modifying the code, which I have not been able to solve so far.
