### ISSUE TITLE
RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 3 is not equal to len(dims) = 4

### ISSUE THREAD

**Issue by utyanndesu** [ruizhecao96/CMGAN#26]
I am a beginner and I would like to ask why I have this problem using the same dataset

**Comment by infiniteknow1** [comment]
I also encountered the same problem, may I ask if you have solved it? Looking forward to your reply
