### ISSUE TITLE
Training can get stuck

### ISSUE THREAD

**Issue by wen0320** [ruizhecao96/CMGAN#34]
Hello
when batch_size=4, mp.spawn(main, args=(2, args), nprocs=2), train_ds, test_ds = dataloader.load_data(args.data_dir, args.batch_size, 8, args.cut_len),When training to the period of 1epoch, GPU=100%, training will be stuck, may I ask you have encountered this, how to solve?

**Comment by SherifAbdulatif** [comment]
So you increase the batch size from 4 to 8 in testing as your question is not clear train_ds, test_ds = dataloader.load_data(args.data_dir, args.batch_size, 8, args.cut_len)?
4 is the maximum we tested 3 can also reproduce very similar results in case you have a limited GPU.

**Comment by wen0320** [comment]
First of all, thank you very much for your reply. And secondly, I'm sorry I didn't make my problem clear. My question is:

When reproducing your code, I often encounter a training stall in the initial epochs.(I'm utilizing two GPUs from a server for training.) The specific issue is that the training process becomes unresponsive, and two GPUs utilization rates remain at 100%.  I suspect this might be due to using DistributedDataParallel for multi-process training, as I don't experience this problem when employing DataParallel for synchronized training.  Unfortunately, I haven't been able to identify a solution myself.  That's why I've reached out to you for assistance.  Are you familiar with this issue or have you encountered it before?

**Comment by coreeey** [comment]
> First of all, thank you very much for your reply. And secondly, I'm sorry I didn't make my problem clear. My question is:
> 
> When reproducing your code, I often encounter a training stall in the initial epochs.(I'm utilizing two GPUs from a server for training.) The specific issue is that the training process becomes unresponsive, and two GPUs utilization rates remain at 100%. I suspect this might be due to using DistributedDataParallel for multi-process training, as I don't experience this problem when employing DataParallel for synchronized training. Unfortunately, I haven't been able to identify a solution myself. That's why I've reached out to you for assistance. Are you familiar with this issue or have you encountered it before?

have you reproduced the result now?

**Comment by taqta** [comment]
> First of all, thank you very much for your reply. And secondly, I'm sorry I didn't make my problem clear. My question is:
> 
> When reproducing your code, I often encounter a training stall in the initial epochs.(I'm utilizing two GPUs from a server for training.) The specific issue is that the training process becomes unresponsive, and two GPUs utilization rates remain at 100%. I suspect this might be due to using DistributedDataParallel for multi-process training, as I don't experience this problem when employing DataParallel for synchronized training. Unfortunately, I haven't been able to identify a solution myself. That's why I've reached out to you for assistance. Are you familiar with this issue or have you encountered it before?

I meet the same problem.  Training stuck in epoch 0, step 500 / 726

**Comment by taqta** [comment]
是这段代码引起训练阻塞
![image](https://github.com/ruizhecao96/CMGAN/assets/99654402/e8d40a91-dc71-46f7-91d3-3b9567551604)
由于loss_metric取值为NONE的时候，进程就会进入else判断，不会进行backward，我推测这会导致gpu之间的不同步。所以只需要在loss_metric取值为none的时候将loss_metric和grad变为0就可以等效替代if else。因此可以把生成loss_metric函数做以下更改：
![image](https://github.com/ruizhecao96/CMGAN/assets/99654402/e48aceef-0011-4b00-aa58-2c593a20647a)
这样就可以避免训练卡住的问题了

**Comment by wen0320** [comment]
> 是这段代码引起训练阻塞 ![image](https://private-user-images.githubusercontent.com/99654402/285658175-e8d40a91-dc71-46f7-91d3-3b9567551604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MDYwNDIsIm5iZiI6MTcwMTQwNTc0MiwicGF0aCI6Ii85OTY1NDQwMi8yODU2NTgxNzUtZThkNDBhOTEtZGM3MS00NmY3LTkxZDMtM2I5NTY3NTUxNjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA0NDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4Zjc3MWZjNGNhYjllMTUwOTdkMmNmMjBlM2NiNTg4NTAwNDdmNjgyMjQ3ZjI2MzgxODU4MDRmYjYxN2I5ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ISYX3L1SIrQCg5xKUAmF4c0LkKZvOZppF51G3sFLHBE) 由于loss_metric取值为NONE的时候，进程就会进入else判断，不会进行backward，我推测这会导致gpu之间的不同步。所以只需要在loss_metric取值为none的时候将loss_metric和grad变为0就可以等效替代if else。因此可以把生成loss_metric函数做以下更改： ![image](https://private-user-images.githubusercontent.com/99654402/285658768-e48aceef-0011-4b00-aa58-2c593a20647a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MDYwNDIsIm5iZiI6MTcwMTQwNTc0MiwicGF0aCI6Ii85OTY1NDQwMi8yODU2NTg3NjgtZTQ4YWNlZWYtMDAxMS00YjAwLWFhNTgtMmM1OTNhMjA2NDdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA0NDIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMmViOTVlMDFlZjRkYmM1ZTc4NWZmNTAzNDU1ZjgzNGVmMGE0Y2UzMTdmMDM3YzFjOTQyMjcxM2MxMGQyYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FbACPJGSW6H_FHLu8Ax8V0NVDK06uW568SbcG7SEN4w) 这样就可以避免训练卡住的问题了

感谢大佬，确实可行。
