### ISSUE TITLE
模型训练的采样率以及显卡训练配置咨询

### ISSUE THREAD

**Issue by Johnsonabuse** [ruizhecao96/CMGAN#47]
您好 很感谢您在语音增强领域做出的贡献 我想问一下您的模型训练的显卡配置是什么 我下载了VCTK-DEMAND数据集 但是训练数据是48khz的 请问您用作训练的数据的samplerate是经过重采样降到16khz吗？

**Comment by BancoLin** [comment]
You have to use high-end GPUs at least 24G RAM, otherwise you have to lower FFT resolution or segment duration. As to VCTK-DEMAND, yes, you need to downsample to 16kHz by yourself.
