### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by p4vlos** [ruizhecao96/CMGAN#6]
Can you please share the code that you organise the VCTK Corpus?
Thanks

**Comment by SherifAbdulatif** [comment]
No need for preparation, you just download the data from [here](https://datashare.ed.ac.uk/handle/10283/1942?show=full). Then you need to point to the directory in [train.py](https://github.com/ruizhecao96/CMGAN/blob/main/src/train.py) and the [dataloader ](https://github.com/ruizhecao96/CMGAN/blob/main/src/data/dataloader.py) will read files and cut the required durations.

**Comment by jamesgrahammv** [comment]
Does the model need to be trained first before use?
Thanks

**Comment by SherifAbdulatif** [comment]
You can find a checkpoint at https://github.com/ruizhecao96/CMGAN/tree/main/src/best_ckpt

**Comment by SherifAbdulatif** [comment]
Solved
