### ISSUE TITLE
The weight

### ISSUE THREAD

**Issue by Blakey-Gavin** [ruizhecao96/CMGAN#8]
Hello, I want to ask if the weight under the path "src best_ckpt" is a trained weight? Because I use it to evaluate my own data results are not good.

**Comment by ruizhecao96** [comment]
> Hello, I want to ask if the weight under the path "src best_ckpt" is a trained weight? Because I use it to evaluate my own data results are not good.
Hello, the src best_ckpt is a trained weight. Can you give me more detail about your data? For different data maybe different pre-processing methods are needed. Or maybe the model is just not powerful enough.

**Comment by Blakey-Gavin** [comment]
Hello, thank you very much for your reply. My general situation is as
follows:

What I test with your weight is a file with noise such as keyboard tapping.
Later, I want to use your model to train the data in musdb18 to get vocals.
The linear addition of vocals and accompaniment is used as the input, and
the label is vocals. However, the effect is not particularly good, and the
SDR value is not very high when used for evaluation.

Have you ever used your model to get vocals from songs in a similar way?

Thank you again and look forward to your reply！

Ruizhe Cao ***@***.***> 于2022年10月20日周四 18:37写道：

**Comment by ruizhecao96** [comment]
I think the bad performance is due to the VCTK-DEMAND dataset doesn't include the keyboard typing noise, and this dataset is not very large, maybe a robust model should be obtained with much more data in the training set.
I am not very familiar with music separation, sorry I am not sure why the performance is not good.

**Comment by Blakey-Gavin** [comment]
OK, I see. Thank you very much for your help.

Best wishes！

Ruizhe Cao ***@***.***> 于2022年11月5日周六 21:45写道：
