### ISSUE TITLE
Chinese

### ISSUE THREAD

**Issue by Rone-98** [ruizhecao96/CMGAN#9]
Sorry for trouble I got to you.I want ask if the model is suitable for Chinese Speech dataset(contain clean and noise)

**Comment by SherifAbdulatif** [comment]
We didn't yet try, but I think it will be very interesting to see the results on Chinese speech. I think it should work if trained on Chinese.

**Comment by BancoLin** [comment]
in most cases the model works well on Chinese because both English and Chinese share many phonetic properties.
